# Bug Hunt Pipeline
# Systematic bug discovery with fresh-eyes exploration, elegant triage, and implementation
#
# Philosophy:
# - Stage 1: Multiple iterations of random exploration with "fresh eyes"
#   Each agent picks code files somewhat randomly, traces execution flows,
#   and does careful, critical analysis to find bugs others missed.
#   Agents document bugs but DO NOT fix them.
#
# - Stage 2: An elegance-style review of all discovered bugs.
#   Agent has full latitude to explore, use subagents for depth,
#   find patterns between bugs, and identify elegant consolidations
#   where one abstraction solves multiple issues.
#   Creates beads for fixes worth implementing.
#
# - Stage 3: Refine the beads to ensure they're well-scoped and clear.
#
# - Stage 4: Work loop to implement the fixes.
#
# Usage:
#   ./scripts/run.sh pipeline templates/bug-hunt.yaml my-session
#
# Customize iterations:
#   --stage-runs=discover:10   # More discovery passes
#   --stage-runs=fix:50        # More implementation iterations

name: bug-hunt
description: Discover bugs with fresh eyes, triage elegantly, refine tasks, implement fixes
version: 1

stages:
  # Stage 1: Explore codebase and document bugs
  # Uses the bug-discovery stage which randomly explores code files,
  # traces imports/exports, and does careful critical analysis.
  # 8 iterations by default - each iteration explores different territory.
  - name: discover
    stage: bug-discovery
    runs: 8
    description: |
      Random exploration with fresh eyes. Each iteration:
      - Picks code files somewhat randomly (not just obvious entry points)
      - Deeply investigates each file's purpose and execution flows
      - Traces imports and exports to understand context
      - Does super careful, methodical, critical review
      - Documents bugs, recommended fixes, and suspicious patterns
      - Does NOT fix anything - discovery only

  # Stage 2: Triage bugs and find elegant solutions
  # Uses the find-elegant-solutions stage which reviews all discovered bugs
  # with full latitude to explore and use subagents.
  # Judgment termination - stops when synthesis is complete.
  - name: elegance
    stage: find-elegant-solutions
    runs: 5
    inputs:
      from: discover
      select: latest
    description: |
      Elegant triage of discovered bugs. Agent has full latitude to:
      - Determine which bugs are critical, worth fixing, nice-to-have, or not worth it
      - Find patterns between bugs that suggest deeper issues
      - Identify elegant solutions where one change fixes multiple bugs
      - Spin up subagents for depth while preserving context for synthesis
      - Create beads for solutions worth implementing

  # Stage 3: Refine the beads
  # Standard bead refinement to ensure tasks are well-scoped.
  - name: refine
    stage: refine-beads
    runs: 3
    inputs:
      from: elegance
      select: latest
    description: |
      Refine beads created during elegance phase.
      Ensure each bead is clear, well-scoped, and actionable.

  # Stage 4: Implement the fixes
  # Standard work loop to execute the refined beads.
  - name: fix
    stage: work
    runs: 25
    inputs:
      from: refine
      select: latest
    description: |
      Traditional Ralph loop - implement the bug fixes.
      Fresh agent each iteration, reads progress file for context.
