# Test Gap Discovery Pipeline
# Systematically find missing tests across the codebase
# Uses fresh-eyes principle: each iteration gets a new agent that might notice what others missed

name: test-gap-discovery
description: Find missing tests, analyze gaps, and create tasks for test coverage

stages:
  # Stage 1: Scan codebase for test coverage gaps (3 iterations with fresh eyes)
  - name: scan
    stage: test-scanner
    runs: 3

  # Stage 2: Analyze and prioritize the gaps found (2 iterations)
  - name: analyze
    stage: test-analyzer
    runs: 2
    inputs:
      from: scan
      select: latest

  # Stage 3: Create beads/tasks for missing tests (1 iteration)
  - name: plan
    stage: test-planner
    runs: 1
    inputs:
      from: analyze
      select: latest
